services:

  postgres:
    image: postgres:16
    container_name: etl-postgres
    environment:
      POSTGRES_DB: etl_db
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:4.0.0
    container_name: etl-kafka
    ports:
      - "9092:9092"

volumes:
  postgres_data: